"""Generate a structured Markdown handover document from a parsed session."""

import os
import subprocess


def git_diff_stat(cwd):
    """Return (diff_stat_text, status_text) or (None, None) if not a repo."""
    if not cwd or not os.path.isdir(cwd):
        return None, None
    try:
        stat = subprocess.run(
            ["git", "-C", cwd, "diff", "--stat"],
            capture_output=True, text=True, timeout=10)
        status = subprocess.run(
            ["git", "-C", cwd, "status", "--short"],
            capture_output=True, text=True, timeout=10)
    except Exception:
        return None, None
    if stat.returncode != 0:
        return None, None
    return stat.stdout.strip() or None, status.stdout.strip() or None


def _timeline(actions, limit=25):
    lines = []
    for a in actions[-limit:]:
        if a["kind"] == "file":
            lines.append("- edited/created: `%s`" % a["detail"])
        elif a["kind"] == "command":
            lines.append("- ran: `%s`" % a["detail"])
        else:
            lines.append("- used tool: `%s`" % a["detail"])
    return lines


def generate(session, include_git=True):
    """Build the HANDOVER.md text for one parsed session dict."""
    s = session
    counts = s.get("counts", {})
    sid = s.get("session_id", "unknown")
    tool = s.get("tool", "unknown")
    started = s.get("started", "") or "(unknown start time)"
    goal = (s.get("goal") or "").strip() or "_No user message found in this transcript._"
    actions = s.get("actions", [])
    errors = s.get("errors", [])
    files = s.get("files", [])

    out = []
    out.append("# Session Handover")
    out.append("")
    out.append("- **Tool:** %s" % tool)
    out.append("- **Session:** `%s`" % sid)
    out.append("- **Started:** %s" % started)
    out.append("- **Messages:** %d" % s.get("messages", 0))
    if s.get("cwd"):
        out.append("- **Working dir:** `%s`" % s["cwd"])
    out.append("")

    out.append("## Goal")
    out.append("")
    out.append(goal)
    out.append("")

    out.append("## What happened")
    out.append("")
    out.append("- File edits/writes: %d" % (counts.get("edits", 0) + counts.get("writes", 0)))
    out.append("- Shell commands run: %d" % counts.get("commands", 0))
    out.append("- Files read/searched: %d" % counts.get("reads", 0))
    out.append("")
    tl = _timeline(actions)
    if tl:
        out.append("### Timeline (last %d actions)" % len(tl))
        out.append("")
        out.extend(tl)
        out.append("")
    elif s.get("messages"):
        out.append("_No tool actions recorded in this transcript._")
        out.append("")

    if files:
        out.append("### Files touched")
        out.append("")
        for f in files[:30]:
            out.append("- `%s`" % f)
        out.append("")

    if include_git:
        stat, status = git_diff_stat(s.get("cwd", ""))
        if stat or status:
            out.append("### Uncommitted changes")
            out.append("")
            if stat:
                out.append("```")
                out.append(stat)
                out.append("```")
                out.append("")
            if status:
                out.append("```")
                out.append(status[:1500])
                out.append("```")
                out.append("")

    if errors:
        out.append("## Errors encountered")
        out.append("")
        for e in errors:
            out.append("- `%s`" % e.replace("\n", " "))
        out.append("")

    out.append("## Open items")
    out.append("")
    out.append("- [ ] _Fill in from the tail of the transcript below, or leave for the next agent._")
    out.append("")

    out.append("## Next steps (for the receiving agent)")
    out.append("")
    out.append("- [ ] Read the goal and timeline above, then verify current state (`git status`, re-run key commands).")
    out.append("- [ ] Continue from the open items; update this file as you go.")
    out.append("")

    out.append("---")
    out.append("_Generated by `session-handover` (heuristic extraction from local transcripts; verify before trusting)._")
    out.append("")

    return "\n".join(out)
